export default {
    'inventory': {
        path: '',
        name: 'Kho Gấu',
        'default': { path: '/inventory', name: 'Tất cả', },
        'add': { path: '/inventory/add', name: 'Thêm mới', },
    },
    'pyc': {
        path: '',
        name: 'Quản lý PYC Điều Quỹ',
        'registration': { path: '/pyc/registration', name: 'Đăng ký', },
        'approval': { path: '/pyc/approval', name: 'Kiểm soát & Phê duyệt', },
    },
    'route-management': {
        path: '',
        name: 'Quản lý Lộ trình',
        'normal': { path: '/route-management/normal', name: 'Lộ trình Bình thường', },
        'urgent': { path: '/route-management/urgent', name: 'Lộ trình Khẩn cấp', },
    },
    'route-tracking': {
        path: '',
        name: 'Theo dõi Lộ trình',
        'car1': { path: '/route-tracking/car1', name: 'PTVC là xe chuyên dùng', },
        'car2': { path: '/route-tracking/car2', name: 'PTVC KHÁC xe chuyên dùng', },
    },
    'category': {
        path: '',
        name: 'Danh mục',
        'area': { path: '/category/area', name: 'Danh mục cụm', },
        'atm-cdm': { path: '/category/atm-cdm', name: 'Danh mục ATM/CDM', },
        'currency': { path: '/category/currency', name: 'Danh mục tiền tệ', },
        'function': { path: '/category/function', name: 'Danh mục chức năng', },
        'nhnn-tctd': { path: '/category/nhnn-tctd', name: 'Danh mục TCTD/NHNN', },
        'orgs': { path: '/category/orgs', name: 'Danh mục đơn vị', },
        'pers': { path: '/category/pers', name: 'Danh mục nhân viên', },
        'priority': { path: '/category/priority', name: 'Danh mục mức độ ưu tiên', },
        'region': { path: '/category/region', name: 'Danh mục vùng', },
        'title': { path: '/category/title', name: 'Danh mục chức danh nhân viên', },
        'vehicle': { path: '/category/vehicle', name: 'Danh mục xe', },
    },
    'report': {
        path: '',
        name: 'Báo cáo KPP',
        'orgs': { path: '/report/orgs', name: 'BC Số lần điều quỹ NV Áp tải', },
        'special': { path: '/report/special', name: 'BC Sổ theo dõi VC HĐB', },
    },
    'user': {
        path: '',
        name: 'Người dùng',
        'change-password': { path: '/user/change-password', name: 'Đổi mật khẩu', },
        'assign-role': { path: '/user/assign-role', name: 'Phân quyền', },
        'reset-password': { path: '/user/reset-password', name: 'Đặt lại mật khẩu', },
        'register': { path: '/user/register', name: 'Đăng ký', },
    },
  }